version: '3.9'
services:
  node:
    container_name: 'node'
    image: 'maks/node'
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    restart: always
    environment:
      PORT: ${PORT}
    networks:
      - maks-defined
  postgres:
    container_name: 'postgres'
    image: 'maks/postgres'
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - maks-defined

networks:
  maks-defined:
    driver: bridge
